base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [

    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

finance_management/urls.py
from django.urls import path
from . import views

app_name = 'finance_management'

urlpatterns = [

    path('account/', views.account, name='account'),
    path('account/add', views.add_account, name='add_account'),
    path('account/<int:account_id>', views.account_details, name='account_details'),

    path('transaction/', views.transaction, name='transaction'),
    path('transaction/add', views.add_transaction, name='add_transaction'),

]

personal_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('finman/', include('finance_management.urls')),
]

base/models.py
from django.db import models

# Create your models here.

finance_management/models.py
from django.db import models
from django.utils import timezone
import uuid

class Account(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, default='Cash')
    balance = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    currency = models.CharField(max_length=4, default='BDT')

    def __str__(self):
        return self.name

class Transaction(models.Model):
    id = models.CharField(max_length=128, primary_key=True, blank=True, unique=True, default=uuid.uuid4)
    timestamp = models.DateTimeField(default=timezone.now())
    account = models.CharField(max_length=128, default='Cash')
    type = models.CharField(max_length=8, default='debit')
    amount = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    remark = models.CharField(max_length=256)

finance_management/forms.py
from django import forms
from django.utils import timezone

class AddAccount(forms.Form):
    name = forms.CharField(max_length=128)
    balance = forms.DecimalField()
    currency = forms.CharField(max_length=4)

class AddTransaction(forms.Form):
    timestamp = forms.DateField(widget=forms.SelectDateWidget, initial=timezone.now())
    accountID = forms.IntegerField()
    type = forms.CharField(max_length=8)
    amount = forms.DecimalField()
    remark = forms.CharField(max_length=256)

base/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_list_or_404, redirect
from django.contrib import messages

def user_login(request):
    context = {}
    next = request.GET.get('next')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if next:
                return redirect(next)
            else:
                messages.success(request, "You have successfully logged in!")
                return redirect('finance_management:account')
        else:
            messages.error(request, "Provide valid credentials.")
            return render(request, 'auth/login.html')
    
    else:
        return render(request, 'auth/login.html', context)


def user_logout(request):
    messages.success(request, "You have been logged out!")
    logout(request)
    return redirect('base:login')

finance_management/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_list_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from .models import *
from .forms import *
from django.contrib.auth.decorators import user_passes_test

@user_passes_test(lambda u: u.is_superuser)
def add_transaction(request):
    all_account_list = Account.objects.all()
    
    if request.method == 'POST':

        form = AddTransaction(request.POST)
        if form.is_valid():
            account = Account.objects.get(id=form.cleaned_data['accountID'])
            print(account)
            transaction = Transaction(
                timestamp = form.cleaned_data['timestamp'],
                account = account.name,
                type = form.cleaned_data['type'],
                amount = form.cleaned_data['amount'],
                remark = form.cleaned_data['remark']
            )
            if form.cleaned_data['type'] == 'Debit':
                account.balance -= form.cleaned_data['amount']
            elif form.cleaned_data['type'] == 'Credit':
                account.balance += form.cleaned_data['amount']
            account.save()
            transaction.save()
            messages.success(request, "Successfully added a new transaction!")
            return redirect('finance_management:transaction')
        else:
            messages.warning(request, "Couldn't add new transaction")
            return redirect('finance_management:transaction')

    else:
        form = AddTransaction()
        return render(request, 'transaction/add_transaction.html', {'form': form, 'account_list': all_account_list})

@user_passes_test(lambda u: u.is_superuser)
def add_account(request):
    if request.method == 'POST':

        form = AddAccount(request.POST)
        if form.is_valid():
            account = Account(
                name = form.cleaned_data['name'],
                balance = form.cleaned_data['balance'],
                currency = form.cleaned_data['currency'],
            )
            account.save()
            messages.success(request, "Successfully added a new account!")
            return redirect('finance_management:account')
        else:
            messages.warning(request, "Couldn't add new account")
            return redirect('finance_management:account')

    else:
        form = AddAccount()
        return render(request, 'account/add_account.html', {'form': form})

@user_passes_test(lambda u: u.is_superuser)
def account(request):
    all_account_list = Account.objects.all()

    if all_account_list is None:
        messages.error(request, "No account exists in the system.")
        return render(request, 'account/account.html', {'account_list': None})
    else:
        return render(request, 'account/account.html', {'account_list': all_account_list})

@user_passes_test(lambda u: u.is_superuser)
def transaction(request):
    all_transaction_list = Transaction.objects.all()

    if all_transaction_list is None:
        messages.error(request, "No transaction exists in the system.")
        return render(request, 'transaction/transaction.html', {'transaction_list': None})
    else:
        return render(request, 'transaction/transaction.html', {'transaction_list': all_transaction_list})

@user_passes_test(lambda u: u.is_superuser)
def account_details(request, account_id):
    account = Account.objects.get(id=account_id)
    all_transaction_list = Transaction.objects.all()
    account_transaction = []
    for transaction in all_transaction_list:
        if transaction.account == account.name:
            account_transaction.append(transaction)
    return render(request, 'account/account_details.html', {'account': account, 'account_transaction': account_transaction})

finance_management/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>FinMan - Sakib Sadman Shajib</title>

    {% block head %}
    {% endblock %}

    <style>
        * {
            box-sizing: border-box;
        }

    </style>

</head>
<body>

    <nav class="navbar navbar-expand navbar-dark bg-dark">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" style="margin: 0 15px">
                    <a class="nav-link" href="{% url 'finance_management:account' %}">Accounts</a>
                </li>
                <li class="nav-item" style="margin: 0 15px">
                    <a class="nav-link" href="{% url 'finance_management:transaction' %}">Transaction</a>
                </li>
            </ul>
            <div class="nav-item">Hello {{request.user.username}}</div>
            <a class="btn btn-danger" href="{% url 'base:logout' %}">Logout</a>
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% else %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {% endif %}
                <strong style="margin: 0 20%; text-align: center">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">
                            &times;
                        </span>
                    </button>
                </strong>
            </div>
        {% endfor %}
    {% endif %}

{% block body %}

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

{% endblock %}

</body>
<footer>
    <p align="right">Developed by <a href="https://scubed.com.bd/"><img src="https://scubed.com.bd/static/SCubedlogo.png" width="64px" height="64px"></a></p>
</footer>
</html>

finance_management/templates/transaction/add_transaction.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block body %}

    <h1 style="width: 100%; margin: 20px; text-align: center">New Transaction</h1>

    <hr>

    <form action="{% url 'finance_management:add_transaction' %}" method="POST">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-group">
                <label for="timestamp">TimeStamp</label>
                {% render_field form.timestamp class+="form-control"%}
            </div>
            <div class="form-group">
                <label for="accountID">Account</label>
                <select class="form-control" title="account" name="accountID">
                    {% for acc in account_list %}
                        <option value={{ acc.id }}>{{ acc }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="type">Type</label>
                <select class="form-control" title="type" name="type">
                        <option>Credit</option>
                        <option>Debit</option>
                </select>
            </div>
            <div class="form-group">
                <label for="amount">Amount</label>
                {% render_field form.amount class+="form-control"%}
            </div>
            <div class="form-group">
                <label for="remark">Remark</label>
                {% render_field form.remark class+="form-control"%}
            </div>
            

            <div class="form-group" style="display: flex; justify-content: space-around; margin: 40px">
                <a href="{% url 'finance_management:transaction' %}" type="button" class="btn btn-secondary">
                    Back
                </a>
                <input type="submit" class="btn btn-primary" value="Submit">
            </div>
        </div>
    </form>

{% endblock %}

{% block styles %}

    a, a:hover {
        color: #be1e2d;
    }

{% endblock %}

{% block head %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}

finance_management/templates/transaction/transaction.html
{% extends 'base.html' %}

{% block body %}

    <h1 style="width: 100%; margin: 20px; text-align: center">Transaction</h1>

    <div style="display: flex; justify-content: space-between; flex-wrap: wrap">

            <a type="button" class="btn col-xl-2 col-lg-2 col-md-4 col-sm-5 col-5" style="margin: 10px; background-color: #373839; font-weight: bold" href="{% url 'finance_management:add_transaction' %}">
                Add Transaction
            </a>
    </div>

    <div style="margin-top: 40px">
    {% if transaction_list %}
        <table class="table table-hover table-bordered">
            <tbody>
                <tr style="text-align: center; background-color: #373839">
                    <th scope="col">ID</th>
                    <th scope="col">TimeStamp</th>
                    <th scope="col">Account</th>
                    <th scope="col">Type</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Remark</th>
                </tr>
                {% for transaction in transaction_list %}
                    <tr>
                    <th>{{ transaction.id }}</th>
                    <td>{{ transaction.timestamp }}</td>
                    <td>{{ transaction.account }}</td>
                    <td>{{ transaction.type }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.remark }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p style="width: 100%; margin: 20px; text-align: center">No transaction present in the database</p>
    {% endif %}
    </div>

{% endblock %}

{% block styles %}

    a, a:hover {
        color: #be1e2d;
    }

{% endblock %}

{% block head %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}